import jsPDF from "jspdf";
import type { SmartFormField } from "../services/smartFormApi";

/**
 * Exports the filled form as a PDF document preserving the exact layout of the uploaded form
 */
export const exportFormAsPdf = (
  formTitle: string,
  fields: SmartFormField[],
  values: Record<string, string>,
  formImagesBase64?: string[],
) => {
  if (!formImagesBase64 || formImagesBase64.length === 0) {
    return exportFormAsPdfFallback(formTitle, fields, values);
  }

  const doc = new jsPDF({ unit: "mm", format: "a4" });

  formImagesBase64.forEach((imgB64, pageIdx) => {
    if (pageIdx > 0) {
      doc.addPage("a4");
    }

    const pageWidth = doc.internal.pageSize.getWidth(); // 210mm
    const pageHeight = doc.internal.pageSize.getHeight(); // 297mm

    // Draw the uploaded form background image
    doc.addImage(imgB64, "JPEG", 0, 0, pageWidth, pageHeight, undefined, "FAST");

    // Get fields belonging to this page
    const pageFields = fields.filter((f) => (f.page ?? 0) === pageIdx);

    pageFields.forEach((field) => {
      let val = values[field.id]?.trim();
      if (!val) return;

      if (field.box_2d) {
        const [ymin, xmin, ymax, xmax] = field.box_2d;

        const boxLeft = (xmin / 1000) * pageWidth;
        const boxTop = (ymin / 1000) * pageHeight;
        const boxWidth = ((xmax - xmin) / 1000) * pageWidth;
        const boxHeight = ((ymax - ymin) / 1000) * pageHeight;

        const isCheckbox = isCheckboxValue(field, val);

        if (isCheckbox) {
          // Draw bold, prominent vector right sign (check mark) inside checkbox box
          drawPdfCheckmark(doc, boxLeft, boxTop, boxWidth, boxHeight);
        } else {
          doc.setFont("helvetica", "bold");
          doc.setTextColor(30, 58, 138); // Dark Navy Blue ink

          // Cap text font size at 10pt max to avoid huge text in table cells
          let fontSize = Math.min(10, Math.max(7.5, boxHeight * 1.5));
          doc.setFontSize(fontSize);

          // Auto-scale font size if text is wider than boxWidth
          let textWidth = doc.getTextWidth(val);
          const maxTextWidth = Math.max(6, boxWidth - 1.5);
          while (textWidth > maxTextWidth && fontSize > 5.5) {
            fontSize -= 0.5;
            doc.setFontSize(fontSize);
            textWidth = doc.getTextWidth(val);
          }

          // Draw text aligned baseline near bottom of line box
          const textX = boxLeft + 1.2;
          const textY = boxTop + boxHeight * 0.80;
          doc.text(val, textX, textY);
        }
      }
    });
  });

  const filename = `${formTitle.toLowerCase().replace(/[^a-z0-9]+/g, "_")}_filled.pdf`;
  doc.save(filename);
};

/**
 * Fallback PDF exporter if no background form image is available
 */
const exportFormAsPdfFallback = (
  formTitle: string,
  fields: SmartFormField[],
  values: Record<string, string>,
) => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let currentY = 20;

  // Header Banner
  doc.setFillColor(79, 70, 229);
  doc.rect(0, 0, pageWidth, 24, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(255, 255, 255);
  doc.text(formTitle || "Completed Form", margin, 15);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`Generated by CollabSpace AI · ${new Date().toLocaleDateString()}`, pageWidth - margin, 15, { align: "right" });

  currentY = 32;

  // Subheader info box
  doc.setFillColor(243, 244, 246);
  doc.rect(margin, currentY, contentWidth, 12, "F");
  doc.setDrawColor(229, 231, 235);
  doc.rect(margin, currentY, contentWidth, 12, "S");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  doc.text("FORM SUMMARY & FILLED DETAILS", margin + 4, currentY + 7.5);

  const filledCount = fields.filter((f) => values[f.id]?.trim()).length;
  doc.setFont("helvetica", "normal");
  doc.text(`Total Fields: ${fields.length}  |  Filled: ${filledCount}`, pageWidth - margin - 4, currentY + 7.5, { align: "right" });

  currentY += 18;

  const col1Width = 65;
  const col2Width = contentWidth - col1Width;

  doc.setFillColor(238, 242, 255);
  doc.rect(margin, currentY, contentWidth, 8, "F");
  doc.setDrawColor(199, 210, 254);
  doc.rect(margin, currentY, contentWidth, 8, "S");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(67, 56, 202);
  doc.text("Field Name", margin + 4, currentY + 5.5);
  doc.text("Filled Value", margin + col1Width + 4, currentY + 5.5);

  currentY += 8;

  fields.forEach((field, index) => {
    const val = values[field.id]?.trim() || "—";
    const label = field.label + (field.required ? " *" : "");

    const splitLabel = doc.splitTextToSize(label, col1Width - 8);
    const splitVal = doc.splitTextToSize(val, col2Width - 8);
    const rowHeight = Math.max(splitLabel.length, splitVal.length) * 5 + 4;

    if (currentY + rowHeight > 275) {
      doc.addPage();
      currentY = 20;
    }

    if (index % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(margin, currentY, contentWidth, rowHeight, "F");
    }

    doc.setDrawColor(229, 231, 235);
    doc.rect(margin, currentY, contentWidth, rowHeight, "S");
    doc.line(margin + col1Width, currentY, margin + col1Width, currentY + rowHeight);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(31, 41, 55);
    doc.text(splitLabel, margin + 4, currentY + 5);

    doc.setFont("helvetica", "normal");
    if (val === "—") {
      doc.setTextColor(156, 163, 175);
    } else {
      doc.setTextColor(17, 24, 39);
    }
    doc.text(splitVal, margin + col1Width + 4, currentY + 5);

    currentY += rowHeight;
  });

  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `CollabSpace AI Smart Forms — Page ${i} of ${totalPages}`,
      pageWidth / 2,
      288,
      { align: "center" }
    );
  }

  const filename = `${formTitle.toLowerCase().replace(/[^a-z0-9]+/g, "_")}_filled.pdf`;
  doc.save(filename);
};

/**
 * Exports the filled form as a Microsoft Word compatible .doc file preserving original uploaded form format
 */
export const exportFormAsDoc = (
  formTitle: string,
  fields: SmartFormField[],
  values: Record<string, string>,
  formImagesBase64?: string[],
) => {
  if (!formImagesBase64 || formImagesBase64.length === 0) {
    return exportFormAsDocFallback(formTitle, fields, values);
  }

  const pagesHtml = formImagesBase64
    .map((imgB64, pageIdx) => {
      const pageFields = fields.filter((f) => (f.page ?? 0) === pageIdx);

      const overlaysHtml = pageFields
        .map((field) => {
          let val = values[field.id]?.trim();
          if (!val || !field.box_2d) return "";

          const [ymin, xmin, ymax, xmax] = field.box_2d;
          const topPct = (ymin / 10).toFixed(2);
          const leftPct = (xmin / 10).toFixed(2);
          const widthPct = ((xmax - xmin) / 10).toFixed(2);
          const heightPct = ((ymax - ymin) / 10).toFixed(2);
          const isCheckbox = isCheckboxValue(field, val);

          if (isCheckbox) {
            return `
              <div style="position: absolute; top: ${topPct}%; left: ${leftPct}%; width: ${widthPct}%; height: ${heightPct}%; z-index: 10; display: flex; align-items: center; justify-content: center; box-sizing: border-box;">
                <span style="font-family: Arial, sans-serif; font-weight: 900; color: #1e3a8a; font-size: 15px; line-height: 1;">
                  &#10004;
                </span>
              </div>
            `;
          }

          return `
            <div style="position: absolute; top: ${topPct}%; left: ${leftPct}%; width: ${widthPct}%; height: ${heightPct}%; z-index: 10; display: flex; align-items: flex-end; padding-left: 3px; padding-bottom: 1px; box-sizing: border-box; overflow: hidden;">
              <span style="font-family: Arial, sans-serif; font-weight: bold; color: #1e3a8a; font-size: 11px; line-height: 1.1; word-break: break-word;">
                ${escapeHtml(val)}
              </span>
            </div>
          `;
        })
        .join("");

      return `
        <div style="position: relative; width: 794px; height: 1123px; margin: 0 auto 30px auto; page-break-after: always; box-shadow: 0 4px 12px rgba(0,0,0,0.15); overflow: hidden; background-color: #ffffff;">
          <img src="${imgB64}" style="position: absolute; top: 0; left: 0; width: 794px; height: 1123px; z-index: 1;" alt="Uploaded Form Page ${pageIdx + 1}" />
          ${overlaysHtml}
        </div>
      `;
    })
    .join("");

  const htmlContent = `
    <!DOCTYPE html>
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8">
      <title>${escapeHtml(formTitle)}</title>
      <style>
        body { font-family: Arial, sans-serif; margin: 20px; background-color: #f3f4f6; color: #1f2937; }
        .page-container { width: 794px; margin: 0 auto; }
      </style>
    </head>
    <body>
      <div class="page-container">
        ${pagesHtml}
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(["\ufeff", htmlContent], {
    type: "application/msword;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const filename = `${formTitle.toLowerCase().replace(/[^a-z0-9]+/g, "_")}_filled.doc`;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

/**
 * Draws a thick, prominent vector check mark (right sign) inside the PDF checkbox box
 */
function drawPdfCheckmark(doc: jsPDF, boxLeft: number, boxTop: number, boxWidth: number, boxHeight: number) {
  const w = Math.max(boxWidth, 3.5);
  const h = Math.max(boxHeight, 3.5);

  doc.setLineWidth(0.85); // Thick, bold vector stroke
  doc.setDrawColor(30, 58, 138); // Crisp Dark Navy Blue

  // Vector stroke points for right sign check mark ✓
  const x1 = boxLeft + w * 0.18;
  const y1 = boxTop + h * 0.48;
  const x2 = boxLeft + w * 0.42;
  const y2 = boxTop + h * 0.78;
  const x3 = boxLeft + w * 0.88;
  const y3 = boxTop + h * 0.18;

  doc.line(x1, y1, x2, y2);
  doc.line(x2, y2, x3, y3);
}

/**
 * Determines whether a field and value represent a checked checkbox choice
 */
export const isCheckboxValue = (field: SmartFormField, val: string | undefined): boolean => {
  if (!val) return false;
  const v = val.trim().toLowerCase();
  if (!v) return false;

  if (["✓", "✔", "x", "true", "yes", "1", "checked", "selected"].includes(v)) {
    return true;
  }

  if (field.type === "checkbox") {
    return true;
  }

  const label = field.label.trim().toLowerCase();
  const fid = field.id.trim().toLowerCase();

  if (label.includes(v) || v.includes(label) || fid.includes(v) || v.includes(fid)) {
    return true;
  }

  return false;
};

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Fallback DOC exporter if no background form image is available
 */
const exportFormAsDocFallback = (
  formTitle: string,
  fields: SmartFormField[],
  values: Record<string, string>,
) => {
  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const tableRowsHtml = fields
    .map((field, idx) => {
      const val = values[field.id]?.trim() || "<i>Not provided</i>";
      const label = field.label + (field.required ? " *" : "");
      const bgColor = idx % 2 === 0 ? "#f9fafb" : "#ffffff";

      return `
        <tr style="background-color: ${bgColor};">
          <td style="padding: 10px 12px; border: 1px solid #e5e7eb; font-weight: bold; width: 35%; color: #1f2937; vertical-align: top;">
            ${escapeHtml(label)}
          </td>
          <td style="padding: 10px 12px; border: 1px solid #e5e7eb; color: #111827; width: 65%; vertical-align: top;">
            ${escapeHtml(val)}
          </td>
        </tr>
      `;
    })
    .join("");

  const htmlContent = `
    <!DOCTYPE html>
    <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
    <head>
      <meta charset="utf-8">
      <title>${escapeHtml(formTitle)}</title>
      <style>
        body { font-family: 'Calibri', 'Arial', sans-serif; margin: 40px; color: #1f2937; line-height: 1.5; }
        .header { background-color: #4f46e5; color: white; padding: 20px; text-align: left; border-radius: 6px; }
        .header h1 { margin: 0; font-size: 22px; font-weight: bold; }
        .header p { margin: 5px 0 0 0; font-size: 12px; opacity: 0.85; }
        .meta { margin-top: 20px; margin-bottom: 20px; padding: 12px 15px; background-color: #f3f4f6; border: 1px solid #e5e7eb; font-size: 13px; color: #4b5563; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 14px; }
        th { background-color: #eef2ff; color: #4338ca; border: 1px solid #c7d2fe; padding: 10px 12px; text-align: left; font-size: 13px; text-transform: uppercase; }
        .footer { margin-top: 40px; font-size: 11px; text-align: center; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 15px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${escapeHtml(formTitle)}</h1>
        <p>Generated by CollabSpace AI · ${dateStr}</p>
      </div>

      <div class="meta">
        <strong>Document Status:</strong> Completed Form Details &nbsp;|&nbsp; <strong>Total Fields:</strong> ${fields.length}
      </div>

      <table>
        <thead>
          <tr>
            <th>Field Label</th>
            <th>Entered Information</th>
          </tr>
        </thead>
        <tbody>
          ${tableRowsHtml}
        </tbody>
      </table>

      <div class="footer">
        Confidential Document · Generated via CollabSpace AI Smart Forms
      </div>
    </body>
    </html>
  `;

  const blob = new Blob(["\ufeff", htmlContent], {
    type: "application/msword;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const filename = `${formTitle.toLowerCase().replace(/[^a-z0-9]+/g, "_")}_filled.doc`;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
